
/****** Object:  Table [dbo].[MOVIMENTO_MANUAL]    Script Date: 13/11/2022 16:32:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [MOVIMENTO_MANUAL]

CREATE TABLE [dbo].[MOVIMENTO_MANUAL](
	[DAT_MES] [int] NOT NULL,
	[DAT_ANO] [int] NOT NULL,
	[NUM_LANCAMENTO] [numeric](18, 0) NOT NULL,
	[COD_PRODUTO] [char](4) NOT NULL,
	[COD_COSIF] [int]  NOT NULL,
	[DES_DESCRICAO] [varchar](50) NOT NULL,
	[DAT_MOVIMENTO] [smalldatetime] NOT NULL,
	[COD_USUARIO] [varchar](15) NOT NULL,
	[VAL_VALOR] [numeric](18, 0) NULL
) ON [PRIMARY]
GO

ALTER TABLE MOVIMENTO_MANUAL
ADD CONSTRAINT MOVIMENTO_MANUAFK FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
ON UPDATE CASCADE
ON DELETE CASCADE;

GO

ALTER TABLE MOVIMENTO_MANUAL
ADD CONSTRAINT MOVIMENTO_MANUA_FK FOREIGN KEY (COD_COSIF) REFERENCES PRODUTO_COSIF (COD_COSIF);
GO




