
/****** Object:  Table [dbo].[PRODUTO]    Script Date: 13/11/2022 16:30:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE PRODUTO

CREATE TABLE [dbo].[PRODUTO](
	[COD_PRODUTO] [char](4) NOT NULL,
	[DES_PRODUTO] [varchar](30) NULL,
	[STA_STATUS] [char](1) NULL,
 CONSTRAINT [PK_Cotacoes] PRIMARY KEY CLUSTERED 
(
	[COD_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


