
/****** Object:  Table [dbo].[PRODUTO_COSIF]    Script Date: 13/11/2022 16:32:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE PRODUTO_COSIF

CREATE TABLE [dbo].[PRODUTO_COSIF](
	[COD_PRODUTO] [char](4) NOT NULL,
	[COD_COSIF]  int IDENTITY(1,1),
	[COD_CLASSIFICACAO] [char](6) NULL,
	[STA_STATUS] [char](1) NULL,
 CONSTRAINT [PK_COD_COSIF] PRIMARY KEY CLUSTERED
(
	[COD_COSIF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE PRODUTO_COSIF
ADD CONSTRAINT PRODUTO_COSIF_FK FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
ON UPDATE CASCADE
ON DELETE CASCADE;


